/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Categories: () => import('#controllers/categories_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Payments: () => import('#controllers/payments_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  Suppliers: () => import('#controllers/suppliers_controller'),
  Transactions: () => import('#controllers/transactions_controller'),
  Users: () => import('#controllers/users_controller'),
}
